---
title: "CS02 - Predicting Annual Air Pollution"
author: "Michael Tang, Vivian Lee, Jennifer Kim, Madeleine Jimenez, and Sean Pao"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: show
---

## Introduction

```{r setup, include=FALSE}
# control global Rmd chunk settings
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

## Questions
- With what accuracy can we predict US annual average air pollution concentrations?
- Extension question

### Load packages

```{r load-packages, message=FALSE}
library(tidyverse)
library(tidymodels)
library(olsrr)
```

## The Data


### Data Import

```{r}
pm <- read_csv("data/pm25_data.csv")
```

### Data Wrangling

```{r}

```


```{r}
# Creating a new column based on the placement of the monitor relative to the 40 degree latitude line
pm <- pm |>
  mutate(n_or_s = case_when(
    lat >= 40 ~ "north",
    lat < 40 ~ "south"
  ))
pm %>% 
  ggplot(aes(y = CMAQ, x = n_or_s)) +
  geom_boxplot()

# Creating a new column based on the placement of the monitor relative to the 100 degree longitude line
pm <- pm |>
  mutate(e_or_w = case_when(
    lon >= -100 ~ "east",
    lon < -100 ~ "west"
  ))
pm %>% 
  ggplot(aes(y = CMAQ, x = e_or_w)) +
  geom_boxplot()

# Creating a new column based on the quadrant of the US the monitor is in
pm <- pm |>
  mutate(quadrant = case_when(
    lon >= -100 & lat >= 40 ~ "northeast",
    lon >= -100 & lat < 40 ~ "southeast",
    lon < -100 & lat >= 40 ~ "northwest",
    lon < -100 & lat < 40 ~ "southwest"
  ))
pm %>% 
  ggplot(aes(y = CMAQ, x = quadrant)) +
  geom_boxplot()
```



## Analysis

```{r}

```


## Results & Discussion 

## Conclusion
